CREATE TABLE `article_moderation_submissions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `article_id` bigint NOT NULL,
  `active_article_id` bigint DEFAULT NULL,
  `submission_token` varchar(64) NOT NULL,
  `title` varchar(255) NOT NULL,
  `summary` varchar(500) DEFAULT NULL,
  `content` longtext NOT NULL,
  `cover_image` varchar(500) DEFAULT NULL,
  `category_id` bigint DEFAULT NULL,
  `topic_id` bigint DEFAULT NULL,
  `allow_comment` tinyint DEFAULT 1,
  `submission_type` varchar(16) NOT NULL,
  `status` varchar(32) NOT NULL,
  `retry_count` int NOT NULL DEFAULT 0,
  `next_retry_at` datetime DEFAULT NULL,
  `processing_started_at` datetime DEFAULT NULL,
  `last_error` varchar(500) DEFAULT NULL,
  `submitted_at` datetime NOT NULL,
  `reviewed_at` datetime DEFAULT NULL,
  `reviewed_by` bigint DEFAULT NULL,
  `review_reason` varchar(500) DEFAULT NULL,
  `manual_action_at` datetime DEFAULT NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_article_moderation_submission_token` (`submission_token`),
  UNIQUE KEY `uk_article_moderation_active_article` (`active_article_id`),
  KEY `idx_article_moderation_due` (`status`, `next_retry_at`),
  CONSTRAINT `fk_article_moderation_submission_article` FOREIGN KEY (`article_id`) REFERENCES `articles` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
